name: Render Pinger
on:
  schedule:
    - cron: '*/5 * * * *'  # Setiap 5 menit
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s "https://nama-bot-anda.onrender.com/secret-ping?key=${{ secrets.SECRET_KEY }}"
